export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const TCHR_LOGIN_SUCCESS = 'TCHR_LOGIN_SUCCESS';
export const TCHR_LOGIN_FAILED = 'TCHR_LOGIN_FAILED';
export const STD_LOGIN_SUCCESS = 'STD_LOGIN_SUCCESS';
export const STD_LOGIN_FAILED = 'STD_LOGIN_FAILED';
